repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
   - id: check-json
   - id: check-yaml
   - id: trailing-whitespace
   - id: end-of-file-fixer
   - id: check-added-large-files
   - id: debug-statements
     language_version: python3

- repo: https://github.com/asottile/reorder_python_imports
  rev: v3.9.0
  hooks:
  - id: reorder-python-imports
  args: [--application-directories=., --py38-plus]

- repo: https://github.com/asottile/pyupgrade
  rev: v3.3.1
  hooks:
  - id: pyupgrade
  args: [--py38-plus]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.1.1
  hooks:
    - id: mypy
      files: ^src/
      args: []

- repo: https://github.com/Joaopeuko/pdtj
  rev: v0.2.1
  hooks:
  - id: pdtj
    args: []
    stages: [commit-msg]

- repo: https://github.com/psf/black
  rev: 23.1.0
  hooks:
    - id: black
      args: [--safe, --line-length=120]

- repo: https://github.com/commitizen-tools/commitizen
  rev: v2.42.1
  hooks:
  - id: commitizen
    stages: [commit-msg]
