name: Publish distributions

# Controls when the workflow will run
on:
  # Triggers the workflow on push request events but only for the master branch
  push:
    branches: [ master ]
    tags:
        - v*
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build-and-publish"
  build-and-publish:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      #Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade setuptools
          pip install build
          pip install twine
          pip install -r requirements.txt

      - name: Run coverage file
        run: |
          coverage run -m pytest --cache-clear --cov-report term-missing --cov=metatrader5EasyT > pytest-coverage.txt

      # Try to publish to Test Pypi
      - name: Publish distribution to Test PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_API_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: |
          python -m build
          python -m build
          twine upload --skip-existing --repository-url https://test.pypi.org/legacy/ dist/*

      # When there is a new tag, publish to PyPi
      - name: Publish distribution to PyPI
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_API_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python -m build
          python -m build
          twine upload dist/*
